-- ==============================================================================
-- REMODA — ESQUEMA COMPLETO Y SEED DATA PARA SUPABASE (POSTGRESQL)
-- Instrucciones: Copia todo este código y pégalo en el "SQL Editor" de tu panel
-- de Supabase, luego presiona "RUN".
-- ==============================================================================

-- 1. LIMPIEZA INICIAL
DROP TABLE IF EXISTS favorites CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS point_transactions CASCADE;
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS custom_requests CASCADE;
DROP TABLE IF EXISTS production_materials CASCADE;
DROP TABLE IF EXISTS production_orders CASCADE;
DROP TABLE IF EXISTS collections CASCADE;
DROP TABLE IF EXISTS product_images CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS coupons CASCADE;
DROP TABLE IF EXISTS delivery_zones CASCADE;
DROP TABLE IF EXISTS branches CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS addresses CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- 2. CREACIÓN DE TABLAS

-- Usuarios / Perfiles
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    phone VARCHAR(255) NULL,
    birth_date DATE NULL,
    role VARCHAR(50) DEFAULT 'customer', -- admin, producer, customer
    points_balance INT DEFAULT 0,
    status VARCHAR(50) DEFAULT 'active',
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Direcciones
CREATE TABLE addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    title VARCHAR(255) DEFAULT 'Principal',
    address VARCHAR(255) NOT NULL,
    city VARCHAR(255) DEFAULT 'Santa Cruz',
    zone VARCHAR(255) NOT NULL,
    reference TEXT NULL,
    is_default BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Categorías
CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) UNIQUE NOT NULL,
    description TEXT NULL,
    image TEXT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    display_order INT DEFAULT 0,
    color VARCHAR(20) NULL,
    banner_image TEXT NULL,
    season VARCHAR(40) NULL,
    material VARCHAR(60) NULL,
    meta_title VARCHAR(255) NULL,
    meta_description TEXT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Sucursales
CREATE TABLE branches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    city VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    phone VARCHAR(255) NOT NULL,
    schedule VARCHAR(255) DEFAULT 'Lun - Sáb: 09:00 - 19:00',
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Zonas de Envío
CREATE TABLE delivery_zones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    city VARCHAR(255) DEFAULT 'Santa Cruz',
    base_cost NUMERIC(8, 2) DEFAULT 15.00,
    estimated_time VARCHAR(255) DEFAULT '24 a 48 horas',
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Cupones
CREATE TABLE coupons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(255) UNIQUE NOT NULL,
    discount_percent INT NULL,
    discount_fixed NUMERIC(8, 2) NULL,
    min_order NUMERIC(8, 2) DEFAULT 0,
    max_uses INT DEFAULT 100,
    used_count INT DEFAULT 0,
    expires_at TIMESTAMP WITH TIME ZONE NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Productos
CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) UNIQUE NOT NULL,
    description TEXT NOT NULL,
    category_id BIGINT REFERENCES categories(id) ON DELETE CASCADE,
    price NUMERIC(8, 2) NOT NULL,
    original_price NUMERIC(8, 2) NULL,
    stock INT DEFAULT 1,
    size VARCHAR(255) DEFAULT 'M',
    color VARCHAR(255) NULL,
    material VARCHAR(255) DEFAULT 'Denim',
    transformation_type VARCHAR(255) DEFAULT 'Reutilizado',
    origin_story TEXT NULL,
    badge VARCHAR(255) NULL,
    rating NUMERIC(3, 2) DEFAULT 5.00,
    reviews_count INT DEFAULT 0,
    is_featured BOOLEAN DEFAULT FALSE,
    is_new BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE,
    is_qc_approved BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Imágenes de Productos
CREATE TABLE product_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
    image_url TEXT NOT NULL,
    is_primary BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Solicitudes de Recolección / Donación de Ropa
CREATE TABLE collections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(255) UNIQUE NOT NULL,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    garment_types VARCHAR(255) NOT NULL,
    approx_quantity INT DEFAULT 1,
    estimated_weight NUMERIC(8, 2) DEFAULT 1.0,
    address_id BIGINT REFERENCES addresses(id) ON DELETE SET NULL,
    pickup_date DATE NOT NULL,
    pickup_slot VARCHAR(255) NOT NULL,
    notes TEXT NULL,
    status VARCHAR(50) DEFAULT 'Solicitada',
    assigned_producer_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    actual_weight NUMERIC(8, 2) NULL,
    actual_quantity INT NULL,
    classification_type VARCHAR(255) NULL,
    material_type VARCHAR(255) NULL,
    quality_grade VARCHAR(255) NULL,
    points_awarded INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Órdenes de Producción
CREATE TABLE production_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(255) UNIQUE NOT NULL,
    producer_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    product_name VARCHAR(255) NOT NULL,
    category_id BIGINT REFERENCES categories(id) ON DELETE CASCADE,
    primary_material VARCHAR(255) DEFAULT 'Denim',
    target_quantity INT DEFAULT 1,
    produced_quantity INT DEFAULT 0,
    scrap_weight NUMERIC(8, 2) DEFAULT 0,
    status VARCHAR(50) DEFAULT 'Pendiente',
    qc_status VARCHAR(50) DEFAULT 'Pendiente',
    qc_notes TEXT NULL,
    material_notes TEXT NULL,
    finished_product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Materiales de Producción
CREATE TABLE production_materials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    production_order_id BIGINT REFERENCES production_orders(id) ON DELETE CASCADE,
    collection_id BIGINT REFERENCES collections(id) ON DELETE SET NULL,
    material_description VARCHAR(255) NOT NULL,
    weight_used NUMERIC(8, 2) DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Solicitudes de Transformación Personalizada
CREATE TABLE custom_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(255) UNIQUE NOT NULL,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    source_garment VARCHAR(255) NOT NULL,
    target_transformation VARCHAR(255) NOT NULL,
    instructions TEXT NOT NULL,
    reference_image TEXT NULL,
    status VARCHAR(50) DEFAULT 'Solicitud',
    quoted_price NUMERIC(8, 2) NULL,
    assigned_producer_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Órdenes de Compra
CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number VARCHAR(255) UNIQUE NOT NULL,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    status VARCHAR(50) DEFAULT 'Pendiente',
    delivery_type VARCHAR(255) DEFAULT 'Envío a domicilio',
    shipping_address_id BIGINT REFERENCES addresses(id) ON DELETE SET NULL,
    branch_id BIGINT REFERENCES branches(id) ON DELETE SET NULL,
    recipient_name VARCHAR(255) NOT NULL,
    recipient_phone VARCHAR(255) NOT NULL,
    delivery_slot VARCHAR(255) NULL,
    delivery_status VARCHAR(50) DEFAULT 'Pendiente',
    delivery_driver VARCHAR(255) NULL,
    subtotal NUMERIC(8, 2) NOT NULL,
    shipping_cost NUMERIC(8, 2) DEFAULT 0,
    discount_amount NUMERIC(8, 2) DEFAULT 0,
    points_redeemed INT DEFAULT 0,
    points_discount NUMERIC(8, 2) DEFAULT 0,
    total NUMERIC(8, 2) NOT NULL,
    payment_method VARCHAR(255) DEFAULT 'QR',
    payment_status VARCHAR(50) DEFAULT 'Pendiente',
    payment_reference VARCHAR(255) NULL,
    notes TEXT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Ítems de Orden
CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
    product_name VARCHAR(255) NOT NULL,
    product_size VARCHAR(255) NULL,
    product_color VARCHAR(255) NULL,
    quantity INT DEFAULT 1,
    unit_price NUMERIC(8, 2) NOT NULL,
    subtotal NUMERIC(8, 2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Pagos
CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
    method VARCHAR(255) DEFAULT 'QR',
    amount NUMERIC(8, 2) NOT NULL,
    status VARCHAR(50) DEFAULT 'Pendiente',
    operation_number VARCHAR(255) NULL,
    paid_at TIMESTAMP WITH TIME ZONE NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Transacciones de Puntos
CREATE TABLE point_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    points INT NOT NULL,
    type VARCHAR(50) NOT NULL,
    description TEXT NOT NULL,
    reference_type VARCHAR(50) NULL,
    reference_id BIGINT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Reseñas / Reseñas de Productos
CREATE TABLE reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    rating INT NOT NULL CHECK (rating >= 1 AND rating <= 5),
    comment TEXT NOT NULL,
    is_approved BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Favoritos
CREATE TABLE favorites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
    UNIQUE(user_id, product_id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);


-- 3. PERMISOS / RLS (Permitir lectura y escritura pública para desarrollo rápido)
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE addresses DISABLE ROW LEVEL SECURITY;
ALTER TABLE categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE branches DISABLE ROW LEVEL SECURITY;
ALTER TABLE delivery_zones DISABLE ROW LEVEL SECURITY;
ALTER TABLE coupons DISABLE ROW LEVEL SECURITY;
ALTER TABLE products DISABLE ROW LEVEL SECURITY;
ALTER TABLE product_images DISABLE ROW LEVEL SECURITY;
ALTER TABLE collections DISABLE ROW LEVEL SECURITY;
ALTER TABLE production_orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE production_materials DISABLE ROW LEVEL SECURITY;
ALTER TABLE custom_requests DISABLE ROW LEVEL SECURITY;
ALTER TABLE orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE order_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE payments DISABLE ROW LEVEL SECURITY;
ALTER TABLE point_transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE reviews DISABLE ROW LEVEL SECURITY;
ALTER TABLE favorites DISABLE ROW LEVEL SECURITY;


-- 4. INSERTAR DATOS INICIALES (SEED DATA)

-- Usuarios
INSERT INTO users (id, name, last_name, email, phone, birth_date, role, points_balance, status, password) VALUES
(1, 'Administrador', 'ReModa', 'admin@remoda.bo', '+591 71234567', '1990-05-15', 'admin', 0, 'active', 'admin123'),
(2, 'Carlos', 'Mendoza', 'productor@remoda.bo', '+591 76543210', '1988-08-20', 'producer', 0, 'active', 'productor123'),
(3, 'Lucía', 'Vargas', 'cliente@remoda.bo', '+591 77889900', '1996-11-03', 'customer', 350, 'active', 'cliente123');

-- Direcciones
INSERT INTO addresses (id, user_id, title, address, city, zone, reference, is_default) VALUES
(1, 3, 'Casa', 'Av. San Martín, Calle 7 Oeste #45', 'Santa Cruz', 'Equipetrol', 'Frente al café cultural, portón negro', true),
(2, 3, 'Oficina', 'Av. Cristo Redentor 3er Anillo Interno', 'Santa Cruz', 'Zona Norte', 'Torre Duo piso 8 oficina 804', false);

-- Sucursales
INSERT INTO branches (id, name, city, address, phone, schedule, is_active) VALUES
(1, 'Tienda ReModa Equipetrol', 'Santa Cruz', 'Av. San Martín esquina Calle 4 Este', '+591 3 3456789', 'Lun - Sáb: 09:30 - 20:00', true),
(2, 'Atelier ReModa Casco Viejo', 'Santa Cruz', 'Calle 24 de Septiembre #180', '+591 3 3321456', 'Lun - Sáb: 09:00 - 19:30', true),
(3, 'Espacio ReModa Sopocachi', 'La Paz', 'Av. 20 de Octubre #2150', '+591 2 2445566', 'Lun - Vie: 10:00 - 19:00, Sáb: 10:00 - 16:00', true);

-- Zonas de Envío
INSERT INTO delivery_zones (id, name, city, base_cost, estimated_time, is_active) VALUES
(1, 'Equipetrol y Sirari', 'Santa Cruz', 12.00, '12 a 24 horas', true),
(2, 'Zona Norte (1er al 5to Anillo)', 'Santa Cruz', 15.00, '24 horas', true),
(3, 'Centro y Casco Viejo', 'Santa Cruz', 15.00, '24 horas', true),
(4, 'Zona Sur y Santos Dumont', 'Santa Cruz', 18.00, '24 a 48 horas', true),
(5, 'Plan 3000 y Villa 1ro de Mayo', 'Santa Cruz', 20.00, '48 horas', true);

-- Cupones
INSERT INTO coupons (id, code, discount_percent, discount_fixed, min_order, max_uses, used_count, is_active) VALUES
(1, 'REMODA10', 10, NULL, 100.00, 500, 18, true),
(2, 'BIENVENIDA20', NULL, 20.00, 120.00, 200, 45, true);

-- Categorías
INSERT INTO categories (id, name, slug, description, image, is_active) VALUES
(1, 'Mochilas', 'mochilas', 'Mochilas urbanas e innovadas elaboradas a partir de denim y lonas recicladas.', 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=600&q=80', true),
(2, 'Camisetas', 'camisetas', 'Prendas básicas de algodón orgánico rescatado con tintes y estampados sostenibles.', 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=600&q=80', true),
(3, 'Jeans', 'jeans', 'Pantalones vaqueros rediseñados, intervenidos y adaptados a estilos contemporáneos.', 'https://images.unsplash.com/photo-1542272604-780c96856592?auto=format&fit=crop&w=600&q=80', true),
(4, 'Bolsos', 'bolsos', 'Bolsos tote y bandoleras confeccionadas con combinaciones de retazos textiles.', 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=600&q=80', true),
(5, 'Chaquetas', 'chaquetas', 'Chaquetas bomber y abrigos intervenidos mediante técnicas de patchwork.', 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=600&q=80', true),
(6, 'Accesorios', 'accesorios', 'Complementos únicos como sombreros, cinturones y collares upcycled.', 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=600&q=80', true),
(7, 'Vestidos', 'vestidos', 'Vestidos confeccionados a partir de cortes de denim y lino reciclado.', 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=600&q=80', true),
(8, 'Carteras', 'carteras', 'Carteras de mano estructuradas con materiales textiles reforzados.', 'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?auto=format&fit=crop&w=600&q=80', true);

-- Productos
INSERT INTO products (id, name, slug, description, category_id, price, original_price, stock, size, color, material, transformation_type, origin_story, badge, rating, reviews_count, is_featured, is_new, is_active, is_qc_approved) VALUES
(1, 'Mochila Denim Revival', 'mochila-denim-revival', 'Mochila urbana de alta resistencia con compartimento acolchado para laptop de hasta 15", forro interno impermeable y bolsillo frontal de acceso rápido.', 1, 185.00, 240.00, 8, 'Talla única', 'Azul Denim Oscuro', 'Denim', 'Transformado', 'Fabricada a partir de 2 jeans reutilizados', 'Más vendido', 4.80, 34, true, false, true, true),
(2, 'Chaqueta Patchwork Bohème', 'chaqueta-patchwork-boheme', 'Chaqueta ligera estilo bomber con cierre frontal metálico, puños elastizados y patrón geométrico de costura invisible.', 5, 320.00, NULL, 4, 'M', 'Terracota / Ocre', 'Mezcla', 'Innovado', 'Ensamblada con retazos de 5 prendas distintas', 'Edición limitada', 4.90, 21, true, false, true, true),
(3, 'Bolso Cartera Terra', 'bolso-cartera-terra', 'Bolso estructurado de mano con correa desmontable, broche magnético bañado en bronce antiguo y forro interior.', 4, 145.00, NULL, 6, 'Talla única', 'Naranja Canela', 'Algodón', 'Transformado', 'Fabricado a partir de pantalones y camisas reutilizadas', 'Nuevo', 4.60, 48, true, true, true, true),
(4, 'Camiseta Re-Basic Ecru', 'camiseta-re-basic-ecru', 'Camiseta clásica de corte unisex elaborada con hilado regenerado 100% algodón. Suave al tacto y transpirable.', 2, 85.00, 110.00, 15, 'L', 'Blanco Hueso', 'Algodón', 'Reutilizado', 'Recuperada y esterilizada con tintes botánicos', 'Nuevo', 4.70, 15, false, true, true, true),
(5, 'Jean Upcycled Cargo Flare', 'jean-upcycled-cargo-flare', 'Pantalón vaquero de tiro alto con corte acampanado y bolsillos cargo laterales adaptados de chamarras militares.', 3, 210.00, NULL, 5, 'S', 'Azul Medio / Verde Oliva', 'Denim', 'Innovado', 'Confeccionado con 2 pantalones vaqueros vintage', '¡Últimas!', 4.85, 19, false, true, true, true),
(6, 'Vestido Midi Denim Patch', 'vestido-midi-denim-patch', 'Vestido casual sin mangas con escote cuadrado, falda en línea A y botonadura central confeccionado con retazos de denim premium.', 7, 260.00, 310.00, 3, 'M', 'Azul Índigo', 'Denim', 'Innovado', 'Creado a partir de 3 faldas vaqueras donadas', 'Edición limitada', 4.95, 12, false, true, true, true),
(7, 'Gargantilla Re-Craft Minimal', 'gargantilla-re-craft-minimal', 'Collar artesanal con colgante de piedra de río engarzada en alambre reciclado y cordoncillo trenzado a mano.', 6, 55.00, NULL, 12, 'Talla única', 'Plata / Índigo', 'Mezcla', 'Transformado', 'Hecho con herrajes reciclados y excedentes de taller', 'Nuevo', 4.90, 27, false, true, true, true),
(8, 'Cartera Sobre Urban Canvas', 'cartera-sobre-urban-canvas', 'Cartera estilo sobre para documentos y tablet, reforzada con forro de lona reciclada y cierre magnético discreto.', 8, 110.00, NULL, 7, 'Talla única', 'Gris Marengo', 'Lana', 'Transformado', 'Elaborada a partir de abrigos de paño en desuso', NULL, 4.50, 9, false, false, true, true),
(9, 'Chamarra Denim Trucker Re-Craft', 'chamarra-denim-trucker-re-craft', 'Chamarra vaquera estilo trucker intervenida con apliques geométricos en espalda y bolsillos reforzados.', 5, 295.00, 350.00, 5, 'L', 'Azul Deslavado', 'Denim', 'Innovado', 'Rescatada de 2 chamarras vintage con acabados artesanales', 'Tendencia', 4.85, 14, true, true, true, true),
(10, 'Mochila Roll-Top Eco Canvas', 'mochila-roll-top-eco-canvas', 'Mochila enrollable de gran capacidad confeccionada con lona militar recuperada y correas de algodón.', 1, 220.00, 270.00, 6, 'Talla única', 'Verde Oliva / Mostaza', 'Algodón', 'Transformado', 'Hecha a partir de carpas de lona militar y excedentes textiles', 'Sostenible', 4.90, 19, true, true, true, true),
(11, 'Polera Gráfica Botanical Dye', 'polera-grafica-botanical-dye', 'Polera de algodón recuperado teñida a mano con extractos de cáscara de cebolla y palta.', 2, 95.00, NULL, 11, 'M', 'Rosa Palo / Terracota', 'Algodón', 'Reutilizado', 'Algodón 100% regenerado con tintes naturales', 'Eco-Tinte', 4.75, 11, false, true, true, true),
(12, 'Pantalón Wide-Leg Denim Art', 'pantalon-wide-leg-denim-art', 'Pantalón holgado de pierna ancha con paneles contrastantes de denim claro y oscuro.', 3, 225.00, 260.00, 4, 'L', 'Azul Dual Tone', 'Denim', 'Innovado', 'Combinación de dos jeans reciclados de tonalidades complementarias', 'Exclusivo', 4.88, 16, true, false, true, true),
(13, 'Tote Bag Eco-Denim Maxi', 'tote-bag-eco-denim-maxi', 'Bolso tote extra amplio con forro impermeable y bolsillos de parche frontales.', 4, 125.00, 150.00, 9, 'Talla única', 'Azul Denim / Crudo', 'Denim', 'Transformado', 'Confeccionado con perneras de vaqueros donados', 'Más vendido', 4.80, 25, false, false, true, true),
(14, 'Bucket Hat Denim Reversible', 'bucket-hat-denim-reversible', 'Sombrero pescador de dos caras: un lado denim oscuro y el otro con estampado artesanal.', 6, 75.00, NULL, 15, 'Talla única', 'Índigo / Estampado', 'Mezcla', 'Transformado', 'Elaborado con recortes de telas sobrantes de corte', 'Nuevo', 4.92, 33, true, true, true, true),
(15, 'Vestido Camisero Upcycled Lino', 'vestido-camisero-upcycled-lino', 'Vestido camisero fresco con lazo ajustable en cintura, botones de madera y detalle de bordado.', 7, 235.00, 280.00, 4, 'S', 'Arena / Beige', 'Algodón', 'Innovado', 'Creado a partir de 2 camisas de lino y algodón donadas', 'Artesanal', 4.88, 18, true, true, true, true),
(16, 'Mini Crossbody Cuero & Denim', 'mini-crossbody-cuero-denim', 'Bolso bandolera compacto con cierre de cremallera metálica y correa ajustable.', 8, 160.00, 195.00, 7, 'Talla única', 'Caramelo / Azul', 'Mezcla', 'Transformado', 'Combinación de retazos de cuero curtido vegetal y denim recuperado', 'Edición limitada', 4.95, 29, true, true, true, true);

-- Imágenes de Productos
INSERT INTO product_images (id, product_id, image_url, is_primary) VALUES
(1, 1, 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80', true),
(2, 1, 'https://images.unsplash.com/photo-1546938576-6e6a64f317cc?auto=format&fit=crop&w=800&q=80', false),
(3, 2, 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=800&q=80', true),
(4, 3, 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=80', true),
(5, 4, 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80', true),
(6, 5, 'https://images.unsplash.com/photo-1542272604-780c96856592?auto=format&fit=crop&w=800&q=80', true),
(7, 6, 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=800&q=80', true),
(8, 7, 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=80', true),
(9, 8, 'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?auto=format&fit=crop&w=800&q=80', true);

-- Recolecciones
INSERT INTO collections (id, code, user_id, garment_types, approx_quantity, estimated_weight, address_id, pickup_date, pickup_slot, notes, status, assigned_producer_id, actual_weight, actual_quantity, classification_type, material_type, quality_grade, points_awarded) VALUES
(1, 'REC-00045', 3, 'Jeans, Chaquetas y Camisas', 6, 3.50, 1, CURRENT_DATE - INTERVAL '5 days', 'Tarde (14:00 - 18:00)', 'Ropa limpia en bolsa ecológica. Tocar timbre de planta baja.', 'Clasificada', 2, 3.80, 6, 'Transformable', 'Denim', 'Excelente', 190),
(2, 'REC-00046', 3, 'Poleras de algodón y vestidos', 4, 2.00, 1, CURRENT_DATE + INTERVAL '2 days', 'Mañana (09:00 - 12:00)', 'Prendas sin roturas, listas para segundo ciclo.', 'Confirmada', 2, NULL, NULL, NULL, NULL, NULL, 0);

-- Órdenes de Producción
INSERT INTO production_orders (id, code, producer_id, product_name, category_id, primary_material, target_quantity, produced_quantity, scrap_weight, status, qc_status, qc_notes, material_notes, finished_product_id) VALUES
(1, 'OP-000125', 2, 'Mochila Denim Revival', 1, 'Denim', 5, 5, 0.40, 'Terminado', 'Aprobado', 'Costuras reforzadas, cierres probados y aprobados para catálogo.', 'Se utilizaron jeans de peso medio 12oz del lote REC-00045.', 1);

-- Materiales de Producción
INSERT INTO production_materials (id, production_order_id, collection_id, material_description, weight_used) VALUES
(1, 1, 1, 'Jeans recolectados lote REC-00045', 3.00);

-- Órdenes de Compra
INSERT INTO orders (id, order_number, user_id, status, delivery_type, shipping_address_id, recipient_name, recipient_phone, delivery_slot, delivery_status, delivery_driver, subtotal, shipping_cost, discount_amount, points_redeemed, points_discount, total, payment_method, payment_status, payment_reference, notes) VALUES
(1, 'RM-000152', 3, 'En camino', 'Envío a domicilio', 1, 'Lucía Vargas', '+591 77889900', '14:00 - 18:00', 'En camino', 'Marcos Morales (Eco-Delivery)', 330.00, 12.00, 33.00, 100, 10.00, 299.00, 'QR', 'Confirmado', 'BNB-QR-98432174', 'Por favor llamar al llegar.');

-- Ítems de Orden
INSERT INTO order_items (id, order_id, product_id, product_name, product_size, product_color, quantity, unit_price, subtotal) VALUES
(1, 1, 1, 'Mochila Denim Revival', 'Talla única', 'Azul Denim Oscuro', 1, 185.00, 185.00),
(2, 1, 3, 'Bolso Cartera Terra', 'Talla única', 'Naranja Canela', 1, 145.00, 145.00);

-- Pagos
INSERT INTO payments (id, order_id, method, amount, status, operation_number, paid_at) VALUES
(1, 1, 'QR', 299.00, 'Confirmado', 'BNB-QR-98432174', NOW() - INTERVAL '1 day');

-- Transacciones de Puntos
INSERT INTO point_transactions (id, user_id, points, type, description, reference_type, reference_id) VALUES
(1, 3, 190, 'donacion', 'Recolección entregada y clasificada #REC-00045 (3.8 kg)', 'collection', 1),
(2, 3, 30, 'compra', 'Puntos acumulados por compra #RM-000152', 'order', 1),
(3, 3, -100, 'canje', 'Descuento canjeado en pedido #RM-000152', 'order', 1);

-- Reseñas
INSERT INTO reviews (id, product_id, user_id, rating, comment, is_approved) VALUES
(1, 1, 3, 5, 'Increíble calidad en las costuras y los detalles del denim reciclado. Me encanta saber que antes eran jeans reales.', true);

-- Ajustar Secuencias de IDs en Postgres para que los autoincrementables continúen correctamente
SELECT setval(pg_get_serial_sequence('users', 'id'), COALESCE(MAX(id), 1)) FROM users;
SELECT setval(pg_get_serial_sequence('addresses', 'id'), COALESCE(MAX(id), 1)) FROM addresses;
SELECT setval(pg_get_serial_sequence('branches', 'id'), COALESCE(MAX(id), 1)) FROM branches;
SELECT setval(pg_get_serial_sequence('delivery_zones', 'id'), COALESCE(MAX(id), 1)) FROM delivery_zones;
SELECT setval(pg_get_serial_sequence('coupons', 'id'), COALESCE(MAX(id), 1)) FROM coupons;
SELECT setval(pg_get_serial_sequence('categories', 'id'), COALESCE(MAX(id), 1)) FROM categories;
SELECT setval(pg_get_serial_sequence('products', 'id'), COALESCE(MAX(id), 1)) FROM products;
SELECT setval(pg_get_serial_sequence('product_images', 'id'), COALESCE(MAX(id), 1)) FROM product_images;
SELECT setval(pg_get_serial_sequence('collections', 'id'), COALESCE(MAX(id), 1)) FROM collections;
SELECT setval(pg_get_serial_sequence('production_orders', 'id'), COALESCE(MAX(id), 1)) FROM production_orders;
SELECT setval(pg_get_serial_sequence('production_materials', 'id'), COALESCE(MAX(id), 1)) FROM production_materials;
SELECT setval(pg_get_serial_sequence('orders', 'id'), COALESCE(MAX(id), 1)) FROM orders;
SELECT setval(pg_get_serial_sequence('order_items', 'id'), COALESCE(MAX(id), 1)) FROM order_items;
SELECT setval(pg_get_serial_sequence('payments', 'id'), COALESCE(MAX(id), 1)) FROM payments;
SELECT setval(pg_get_serial_sequence('point_transactions', 'id'), COALESCE(MAX(id), 1)) FROM point_transactions;
SELECT setval(pg_get_serial_sequence('reviews', 'id'), COALESCE(MAX(id), 1)) FROM reviews;
